version: "3.8"
services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: ./docker/app/Dockerfile
  #   container_name: kreol-api
  #   restart: unless-stopped
  #   ports:
  #     - 4000:4000
  #   env_file: .env.local
  #   links:
  #     - db
  #   depends_on:
  #     - db

  db:
    image: mongo:5.0
    container_name: kreol-db
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./docker/db/data:/data/db
      - ./docker/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      MONGO_INITDB_DATABASE: kreol
      MONGO_INITDB_ROOT_USERNAME: kreol
      MONGO_INITDB_ROOT_PASSWORD: password

  db-seed:
    build: ./docker/db
    container_name: kreol-db-seed
    links:
      - db

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: kreol-mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: kreol
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://kreol:password@db
    depends_on:
      - db
